// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 94js2uNtUqpbuto4RjVnjs
// Component: 8VAXs8-di9
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import TestBut from "../../TestBut"; // plasmic-import: Ska_iDjcL1/component

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_library_plasmic_color_type_css from "../library_plasmic_color_type/plasmic_library_plasmic_color_type.module.css"; // plasmic-import: seaQhLVS4bbjiGvJJrRwyL/projectcss
import projectcss from "./plasmic_simple_light_landing_page.module.css"; // plasmic-import: 94js2uNtUqpbuto4RjVnjs/projectcss
import sty from "./PlasmicTestComp.module.css"; // plasmic-import: 8VAXs8-di9/css

export type PlasmicTestComp__VariantMembers = {};
export type PlasmicTestComp__VariantsArgs = {};
type VariantPropType = keyof PlasmicTestComp__VariantsArgs;
export const PlasmicTestComp__VariantProps = new Array<VariantPropType>();

export type PlasmicTestComp__ArgsType = {};
type ArgPropType = keyof PlasmicTestComp__ArgsType;
export const PlasmicTestComp__ArgProps = new Array<ArgPropType>();

export type PlasmicTestComp__OverridesType = {
  root?: p.Flex<"div">;
  testBut?: p.Flex<typeof TestBut>;
};

export interface DefaultTestCompProps {
  className?: string;
}

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());
const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    await promise;
  });

function PlasmicTestComp__RenderFunc(props: {
  variants: PlasmicTestComp__VariantsArgs;
  args: PlasmicTestComp__ArgsType;
  overrides: PlasmicTestComp__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const currentUser = p.useCurrentUser?.() || {};

  const [$queries, setDollarQueries] = React.useState({});

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_library_plasmic_color_type_css.plasmic_tokens,
        sty.root
      )}
    >
      <TestBut
        data-plasmic-name={"testBut"}
        data-plasmic-override={overrides.testBut}
        className={classNames("__wab_instance", sty.testBut)}
      />
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "testBut"],
  testBut: ["testBut"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  testBut: typeof TestBut;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicTestComp__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicTestComp__VariantsArgs;
    args?: PlasmicTestComp__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicTestComp__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicTestComp__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicTestComp__ArgProps,
          internalVariantPropNames: PlasmicTestComp__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicTestComp__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicTestComp";
  } else {
    func.displayName = `PlasmicTestComp.${nodeName}`;
  }
  return func;
}

export const PlasmicTestComp = Object.assign(
  // Top-level PlasmicTestComp renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    testBut: makeNodeComponent("testBut"),

    // Metadata about props expected for PlasmicTestComp
    internalVariantProps: PlasmicTestComp__VariantProps,
    internalArgProps: PlasmicTestComp__ArgProps
  }
);

export default PlasmicTestComp;
/* prettier-ignore-end */
